////***From Data to Matrix***///

/////Objective: Convert a raw dataset into a NumPy matrix and perform basic transformations////

In [9]:
import numpy as np
import pandas as pd
student_grades=[["Anu",80,54],["priya",57,80],["vishnu",89,45],["ram",66,70]]
arr=np.array(student_grades)
print(arr)


[['Anu' '80' '54']
 ['priya' '57' '80']
 ['vishnu' '89' '45']
 ['ram' '66' '70']]


//////convert to matrix////

In [10]:
name=np.array([row[0]for row in arr]).reshape(-1,1)
score=[row[1:] for row in arr]
matrix=np.array(score,dtype=float)
print(matrix)
column=["maths","science"]
## using dataframe to display with column name###
df=pd.DataFrame(matrix,columns=column)
print(df)


[[80. 54.]
 [57. 80.]
 [89. 45.]
 [66. 70.]]
   maths  science
0   80.0     54.0
1   57.0     80.0
2   89.0     45.0
3   66.0     70.0


/////Add a new feature(column)///

In [11]:
sports_score=np.array([50,40,56,78]).reshape(-1,1) ## another way sports_score=[[50],[40],[56],[78]]
new_column=np.hstack((matrix,sports_score))
print(new_column)
###using dataframe####
column=["maths","science","sports_score"]
df1=pd.DataFrame(new_column,columns=column,index=[row[0]for row in arr]) ###index value always starts in 0,index(0,4)
print(df1)


[[80. 54. 50.]
 [57. 80. 40.]
 [89. 45. 56.]
 [66. 70. 78.]]
        maths  science  sports_score
Anu      80.0     54.0          50.0
priya    57.0     80.0          40.0
vishnu   89.0     45.0          56.0
ram      66.0     70.0          78.0


/////calculating a new feature average/////

In [12]:
average=np.mean(new_column,axis=1).reshape(-1,1)
new_matrix=np.hstack((new_column,average))
print(new_matrix)

[[80.         54.         50.         61.33333333]
 [57.         80.         40.         59.        ]
 [89.         45.         56.         63.33333333]
 [66.         70.         78.         71.33333333]]


///final output///


In [14]:

print("Display with Names")
output=np.hstack((name,new_matrix))
print(output)
new_matrix[:, 0] *= 1.1
print("After adding Scaler")
print(new_matrix)


Display with Names
[['Anu' '80.0' '54.0' '50.0' '61.333333333333336']
 ['priya' '57.0' '80.0' '40.0' '59.0']
 ['vishnu' '89.0' '45.0' '56.0' '63.333333333333336']
 ['ram' '66.0' '70.0' '78.0' '71.33333333333333']]
After adding Scaler
[[88.         54.         50.         61.33333333]
 [62.7        80.         40.         59.        ]
 [97.9        45.         56.         63.33333333]
 [72.6        70.         78.         71.33333333]]
