/////** Basic Data scaling**//

////Objective: Scale a 2D dataset matrix (columns are features) by subtracting the mean and dividing by the standard deviation of each feature///

In [ ]:
import numpy as np
M=np.array([[1,2,3],
[4,5,6],
[7,8,9]])
print("Original array is:\n",M)
##mean calculation###
mean=M.mean(axis=0)
std=M.std(axis=0)
print("mean value is:\n",mean)
print("standared deviation of the value is:\n",std)
###vectorized subtraction and diviation###
vec=(M-mean)/std
print("vectorized value is:\n",vec)





[[1 2 3]
 [4 5 6]
 [7 8 9]]
mean value is:
 [4. 5. 6.]
standared deviation of the value is:
 [2.44948974 2.44948974 2.44948974]
vectorized value is:
 [[-1.22474487 -1.22474487 -1.22474487]
 [ 0.          0.          0.        ]
 [ 1.22474487  1.22474487  1.22474487]]
